[package]
name = "blink-cmp-fuzzy"
version = "0.1.0"
edition = "2021"

[lib]
path = "lua/blink/cmp/fuzzy/lib.rs"
crate-type = ["cdylib"]

[dependencies]
regex = "1.10.5"
lazy_static = "1.5.0"
frizbee = { git = "https://github.com/saghen/frizbee" }
serde = { version = "1.0.204", features = ["derive"] }
heed = "0.20.3"
mlua = { version = "0.10.0-rc.1", features = ["module", "luajit"] }
